"""baseline schema (v1 through v107)

Revision ID: 04d93c4b75f0
Revises: 
Create Date: 2026-09-10 11:31:18.945348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04d93c4b75f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('session_key', sa.String(length=255), nullable=False),
    sa.Column('messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_owner_id'), 'api_keys', ['owner_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('app_share_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('row_filter', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_share_grants_app_id'), 'app_share_grants', ['app_id'], unique=False)
    op.create_index(op.f('ix_app_share_grants_owner_id'), 'app_share_grants', ['owner_id'], unique=False)
    op.create_index(op.f('ix_app_share_grants_token'), 'app_share_grants', ['token'], unique=True)
    op.create_table('apps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_dataset_id'), 'apps', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_apps_name'), 'apps', ['name'], unique=True)
    op.create_index(op.f('ix_apps_owner_id'), 'apps', ['owner_id'], unique=False)
    op.create_index(op.f('ix_apps_slug'), 'apps', ['slug'], unique=True)
    op.create_index(op.f('ix_apps_status'), 'apps', ['status'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_execution_id'), 'artifacts', ['execution_id'], unique=False)
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    op.create_index(op.f('ix_artifacts_workflow_id'), 'artifacts', ['workflow_id'], unique=False)
    op.create_table('business_process_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('ref', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('entered_state_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_process_instances_owner_id'), 'business_process_instances', ['owner_id'], unique=False)
    op.create_index(op.f('ix_business_process_instances_process_id'), 'business_process_instances', ['process_id'], unique=False)
    op.create_index(op.f('ix_business_process_instances_state'), 'business_process_instances', ['state'], unique=False)
    op.create_table('business_process_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('from_state', sa.String(length=60), nullable=True),
    sa.Column('to_state', sa.String(length=60), nullable=False),
    sa.Column('transition', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=140), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_process_transitions_instance_id'), 'business_process_transitions', ['instance_id'], unique=False)
    op.create_index(op.f('ix_business_process_transitions_owner_id'), 'business_process_transitions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_business_process_transitions_process_id'), 'business_process_transitions', ['process_id'], unique=False)
    op.create_table('business_processes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_processes_owner_id'), 'business_processes', ['owner_id'], unique=False)
    op.create_table('chain_report_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cadence_seconds', sa.Integer(), nullable=False),
    sa.Column('to', sa.String(length=500), nullable=False),
    sa.Column('history_limit', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=120), nullable=False),
    sa.Column('chains', sa.String(length=500), nullable=False),
    sa.Column('system', sa.String(length=120), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_report_schedules_owner_id'), 'chain_report_schedules', ['owner_id'], unique=True)
    op.create_table('channel_endpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('handler_workflow_id', sa.String(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('events_received', sa.Integer(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_endpoints_owner_id'), 'channel_endpoints', ['owner_id'], unique=False)
    op.create_index(op.f('ix_channel_endpoints_provider'), 'channel_endpoints', ['provider'], unique=False)
    op.create_table('channel_queue_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('queue_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=140), nullable=False),
    sa.Column('address', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_queue_entries_owner_id'), 'channel_queue_entries', ['owner_id'], unique=False)
    op.create_index(op.f('ix_channel_queue_entries_queue_id'), 'channel_queue_entries', ['queue_id'], unique=False)
    op.create_index(op.f('ix_channel_queue_entries_session_id'), 'channel_queue_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_channel_queue_entries_status'), 'channel_queue_entries', ['status'], unique=False)
    op.create_table('channel_queues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('meeting_id', sa.String(length=36), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_queues_owner_id'), 'channel_queues', ['owner_id'], unique=False)
    op.create_index(op.f('ix_channel_queues_state'), 'channel_queues', ['state'], unique=False)
    op.create_table('credential_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('credential_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_events_created_at'), 'credential_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_credential_events_credential_id'), 'credential_events', ['credential_id'], unique=False)
    op.create_index(op.f('ix_credential_events_owner_id'), 'credential_events', ['owner_id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('data_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_owner_id'), 'credentials', ['owner_id'], unique=False)
    op.create_table('dashboard_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dashboard_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_audit_events_created_at'), 'dashboard_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_events_dashboard_id'), 'dashboard_audit_events', ['dashboard_id'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_name'), 'dashboards', ['name'], unique=True)
    op.create_index(op.f('ix_dashboards_owner_id'), 'dashboards', ['owner_id'], unique=False)
    op.create_index(op.f('ix_dashboards_slug'), 'dashboards', ['slug'], unique=True)
    op.create_index(op.f('ix_dashboards_status'), 'dashboards', ['status'], unique=False)
    op.create_table('dataset_contract_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('columns_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('on_violation', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_contract_revisions_created_at'), 'dataset_contract_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_dataset_contract_revisions_dataset_id'), 'dataset_contract_revisions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_contract_revisions_owner_id'), 'dataset_contract_revisions', ['owner_id'], unique=False)
    op.create_table('dataset_contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('columns_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('on_violation', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_contracts_dataset_id'), 'dataset_contracts', ['dataset_id'], unique=True)
    op.create_index(op.f('ix_dataset_contracts_owner_id'), 'dataset_contracts', ['owner_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('node_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_created_at'), 'dataset_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_owner_id'), 'dataset_versions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_workflow_id'), 'dataset_versions', ['workflow_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('schema_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('certified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steward', sa.String(length=120), nullable=True),
    sa.Column('domain', sa.String(length=80), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('sensitivity', sa.String(length=20), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=True)
    op.create_index(op.f('ix_datasets_owner_id'), 'datasets', ['owner_id'], unique=False)
    op.create_table('deployment_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('model_registry_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_revisions_deployment_id'), 'deployment_revisions', ['deployment_id'], unique=False)
    op.create_table('deployment_token_hits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quota_day', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_token_hits_token_id'), 'deployment_token_hits', ['token_id'], unique=False)
    op.create_table('deployment_token_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('rate_per_min', sa.Integer(), nullable=True),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_token_policies_token_id'), 'deployment_token_policies', ['token_id'], unique=True)
    op.create_table('deployment_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_tokens_deployment_id'), 'deployment_tokens', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_tokens_key_hash'), 'deployment_tokens', ['key_hash'], unique=False)
    op.create_index(op.f('ix_deployment_tokens_owner_id'), 'deployment_tokens', ['owner_id'], unique=False)
    op.create_table('env_variables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_env_variables_key'), 'env_variables', ['key'], unique=True)
    op.create_index(op.f('ix_env_variables_owner_id'), 'env_variables', ['owner_id'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_owner_id'), 'folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_table('grant_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=True),
    sa.Column('grant_name', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grant_audit_events_app_id'), 'grant_audit_events', ['app_id'], unique=False)
    op.create_index(op.f('ix_grant_audit_events_created_at'), 'grant_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_grant_audit_events_grant_id'), 'grant_audit_events', ['grant_id'], unique=False)
    op.create_table('ingestion_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('watermark', sa.String(length=120), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'key', name='uq_ingestion_state')
    )
    op.create_index(op.f('ix_ingestion_states_dataset_id'), 'ingestion_states', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ingestion_states_owner_id'), 'ingestion_states', ['owner_id'], unique=False)
    op.create_table('interaction_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('participant_id', sa.String(length=180), nullable=False),
    sa.Column('participant_name', sa.String(length=180), nullable=False),
    sa.Column('handler_workflow_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=180), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_conversations_channel'), 'interaction_conversations', ['channel'], unique=False)
    op.create_index(op.f('ix_interaction_conversations_owner_id'), 'interaction_conversations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_interaction_conversations_state'), 'interaction_conversations', ['state'], unique=False)
    op.create_table('interaction_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_messages_conversation_id'), 'interaction_messages', ['conversation_id'], unique=False)
    op.create_table('media_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('ref_kind', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_sessions_kind'), 'media_sessions', ['kind'], unique=False)
    op.create_index(op.f('ix_media_sessions_owner_id'), 'media_sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_sessions_ref_id'), 'media_sessions', ['ref_id'], unique=False)
    op.create_index(op.f('ix_media_sessions_state'), 'media_sessions', ['state'], unique=False)
    op.create_table('model_deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('model_registry_id', sa.String(length=36), nullable=False),
    sa.Column('serving_mode', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_deployments_enabled'), 'model_deployments', ['enabled'], unique=False)
    op.create_index(op.f('ix_model_deployments_model_registry_id'), 'model_deployments', ['model_registry_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_owner_id'), 'model_deployments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_workflow_id'), 'model_deployments', ['workflow_id'], unique=False)
    op.create_table('model_systems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('modalities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_systems_owner_id'), 'model_systems', ['owner_id'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('events', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('webhook_url', sa.String(length=2000), nullable=False),
    sa.Column('headers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fire_count', sa.Integer(), nullable=False),
    sa.Column('last_status', sa.String(length=10), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_rules_owner_id'), 'notification_rules', ['owner_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_workflow_id'), 'notification_rules', ['workflow_id'], unique=False)
    op.create_table('pack_registries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=10), nullable=True),
    sa.Column('last_summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pack_registries_owner_id'), 'pack_registries', ['owner_id'], unique=False)
    op.create_table('py8n_systems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('lifecycle', sa.String(length=20), nullable=False),
    sa.Column('source_solution_slug', sa.String(length=140), nullable=True),
    sa.Column('upgraded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py8n_systems_lifecycle'), 'py8n_systems', ['lifecycle'], unique=False)
    op.create_index(op.f('ix_py8n_systems_owner_id'), 'py8n_systems', ['owner_id'], unique=False)
    op.create_table('report_delivery_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('attached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_delivery_events_created_at'), 'report_delivery_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_delivery_events_report_id'), 'report_delivery_events', ['report_id'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('fmt', sa.String(length=10), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('delivery_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fire_count', sa.Integer(), nullable=False),
    sa.Column('last_status', sa.String(length=10), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('last_artifact_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_reports_owner_id'), 'scheduled_reports', ['owner_id'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_source_id'), 'scheduled_reports', ['source_id'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('outcomes_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pack_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('docs', sa.Text(), nullable=False),
    sa.Column('installs', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_category'), 'solutions', ['category'], unique=False)
    op.create_index(op.f('ix_solutions_owner_id'), 'solutions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_solutions_slug'), 'solutions', ['slug'], unique=True)
    op.create_table('system_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('persona', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('spec_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('messages_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('built_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_drafts_owner_id'), 'system_drafts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_system_drafts_status'), 'system_drafts', ['status'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=180), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=180), nullable=False),
    sa.Column('correlation_id', sa.String(length=180), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_correlation_id'), 'system_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_owner_id'), 'system_events', ['owner_id'], unique=False)
    op.create_index(op.f('ix_system_events_session_id'), 'system_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_system_events_source'), 'system_events', ['source'], unique=False)
    op.create_index(op.f('ix_system_events_type'), 'system_events', ['type'], unique=False)
    op.create_table('trained_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=60), nullable=False),
    sa.Column('task', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('reference_stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_name', sa.String(length=120), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    op.create_index(op.f('ix_trained_models_active'), 'trained_models', ['active'], unique=False)
    op.create_index(op.f('ix_trained_models_name'), 'trained_models', ['name'], unique=False)
    op.create_index(op.f('ix_trained_models_owner_id'), 'trained_models', ['owner_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('voice_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('greeting_text', sa.Text(), nullable=False),
    sa.Column('asr_provider', sa.String(length=40), nullable=False),
    sa.Column('tts_provider', sa.String(length=40), nullable=False),
    sa.Column('tts_voice', sa.String(length=80), nullable=False),
    sa.Column('tts_format', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('barge_in', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('handler_workflow_id', sa.String(length=36), nullable=True),
    sa.Column('knowledge_dataset_id', sa.String(length=36), nullable=True),
    sa.Column('knowledge_text_column', sa.String(length=80), nullable=True),
    sa.Column('knowledge_answer_column', sa.String(length=80), nullable=True),
    sa.Column('knowledge_top_k', sa.Integer(), nullable=False),
    sa.Column('brain', sa.String(length=20), nullable=False),
    sa.Column('brain_provider', sa.String(length=40), nullable=False),
    sa.Column('brain_model', sa.String(length=120), nullable=False),
    sa.Column('llm_credential_id', sa.String(length=36), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_agents_owner_id'), 'voice_agents', ['owner_id'], unique=False)
    op.create_table('voice_campaign_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('address', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('call_control_id', sa.String(length=180), nullable=False),
    sa.Column('last_error', sa.String(length=400), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dialed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_campaign_targets_campaign_id'), 'voice_campaign_targets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_voice_campaign_targets_owner_id'), 'voice_campaign_targets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_voice_campaign_targets_session_id'), 'voice_campaign_targets', ['session_id'], unique=False)
    op.create_index(op.f('ix_voice_campaign_targets_status'), 'voice_campaign_targets', ['status'], unique=False)
    op.create_table('voice_campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_campaigns_owner_id'), 'voice_campaigns', ['owner_id'], unique=False)
    op.create_index(op.f('ix_voice_campaigns_status'), 'voice_campaigns', ['status'], unique=False)
    op.create_table('voice_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_events_session_id'), 'voice_events', ['session_id'], unique=False)
    op.create_table('voice_meeting_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('participant_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('author', sa.String(length=140), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_meeting_messages_meeting_id'), 'voice_meeting_messages', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_voice_meeting_messages_owner_id'), 'voice_meeting_messages', ['owner_id'], unique=False)
    op.create_table('voice_meeting_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=140), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=180), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('call_control_id', sa.String(length=180), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.String(length=400), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_meeting_participants_meeting_id'), 'voice_meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_voice_meeting_participants_owner_id'), 'voice_meeting_participants', ['owner_id'], unique=False)
    op.create_index(op.f('ix_voice_meeting_participants_session_id'), 'voice_meeting_participants', ['session_id'], unique=False)
    op.create_table('voice_meeting_recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_meeting_recordings_meeting_id'), 'voice_meeting_recordings', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_voice_meeting_recordings_owner_id'), 'voice_meeting_recordings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_voice_meeting_recordings_state'), 'voice_meeting_recordings', ['state'], unique=False)
    op.create_table('voice_meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_meetings_owner_id'), 'voice_meetings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_voice_meetings_state'), 'voice_meetings', ['state'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('call_ref', sa.String(length=180), nullable=False),
    sa.Column('from_ref', sa.String(length=180), nullable=False),
    sa.Column('to_ref', sa.String(length=180), nullable=False),
    sa.Column('handler_workflow_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('end_reason', sa.String(length=40), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_sessions_conversation_id'), 'voice_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_owner_id'), 'voice_sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_state'), 'voice_sessions', ['state'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('graph', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('error_workflow_id', sa.String(length=36), nullable=True),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('policy_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_folder_id'), 'workflows', ['folder_id'], unique=False)
    op.create_index(op.f('ix_workflows_owner_id'), 'workflows', ['owner_id'], unique=False)
    op.create_table('model_system_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_system_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_system_id'], ['model_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_system_id', 'kind', 'ref_id', name='uq_model_system_component')
    )
    op.create_index(op.f('ix_model_system_components_kind'), 'model_system_components', ['kind'], unique=False)
    op.create_index(op.f('ix_model_system_components_model_system_id'), 'model_system_components', ['model_system_id'], unique=False)
    op.create_index(op.f('ix_model_system_components_ref_id'), 'model_system_components', ['ref_id'], unique=False)
    op.create_table('system_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['py8n_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_api_keys_key_hash'), 'system_api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_system_api_keys_system_id'), 'system_api_keys', ['system_id'], unique=False)
    op.create_table('system_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['py8n_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'kind', 'ref_id', name='uq_system_component')
    )
    op.create_index(op.f('ix_system_components_kind'), 'system_components', ['kind'], unique=False)
    op.create_index(op.f('ix_system_components_ref_id'), 'system_components', ['ref_id'], unique=False)
    op.create_index(op.f('ix_system_components_system_id'), 'system_components', ['system_id'], unique=False)
    op.create_table('system_deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('branding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ping_ok', sa.Boolean(), nullable=True),
    sa.Column('last_ping_ms', sa.Integer(), nullable=True),
    sa.Column('last_ping_code', sa.Integer(), nullable=True),
    sa.Column('last_ping_detail', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['py8n_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_deployments_domain'), 'system_deployments', ['domain'], unique=True)
    op.create_index(op.f('ix_system_deployments_system_id'), 'system_deployments', ['system_id'], unique=True)
    op.create_table('system_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['py8n_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'user_id', name='uq_system_member')
    )
    op.create_index(op.f('ix_system_members_system_id'), 'system_members', ['system_id'], unique=False)
    op.create_index(op.f('ix_system_members_user_id'), 'system_members', ['user_id'], unique=False)
    op.create_table('system_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('verb', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=180), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['py8n_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_operations_created_at'), 'system_operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_operations_system_id'), 'system_operations', ['system_id'], unique=False)
    op.create_table('workflow_execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('trigger_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('node_runs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('context_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_execution_logs_started_at'), 'workflow_execution_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_execution_logs_status'), 'workflow_execution_logs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_execution_logs_workflow_id'), 'workflow_execution_logs', ['workflow_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('graph', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_execution_logs_workflow_id'), table_name='workflow_execution_logs')
    op.drop_index(op.f('ix_workflow_execution_logs_status'), table_name='workflow_execution_logs')
    op.drop_index(op.f('ix_workflow_execution_logs_started_at'), table_name='workflow_execution_logs')
    op.drop_table('workflow_execution_logs')
    op.drop_index(op.f('ix_system_operations_system_id'), table_name='system_operations')
    op.drop_index(op.f('ix_system_operations_created_at'), table_name='system_operations')
    op.drop_table('system_operations')
    op.drop_index(op.f('ix_system_members_user_id'), table_name='system_members')
    op.drop_index(op.f('ix_system_members_system_id'), table_name='system_members')
    op.drop_table('system_members')
    op.drop_index(op.f('ix_system_deployments_system_id'), table_name='system_deployments')
    op.drop_index(op.f('ix_system_deployments_domain'), table_name='system_deployments')
    op.drop_table('system_deployments')
    op.drop_index(op.f('ix_system_components_system_id'), table_name='system_components')
    op.drop_index(op.f('ix_system_components_ref_id'), table_name='system_components')
    op.drop_index(op.f('ix_system_components_kind'), table_name='system_components')
    op.drop_table('system_components')
    op.drop_index(op.f('ix_system_api_keys_system_id'), table_name='system_api_keys')
    op.drop_index(op.f('ix_system_api_keys_key_hash'), table_name='system_api_keys')
    op.drop_table('system_api_keys')
    op.drop_index(op.f('ix_model_system_components_ref_id'), table_name='model_system_components')
    op.drop_index(op.f('ix_model_system_components_model_system_id'), table_name='model_system_components')
    op.drop_index(op.f('ix_model_system_components_kind'), table_name='model_system_components')
    op.drop_table('model_system_components')
    op.drop_index(op.f('ix_workflows_owner_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_folder_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_voice_sessions_state'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_owner_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_conversation_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_index(op.f('ix_voice_meetings_state'), table_name='voice_meetings')
    op.drop_index(op.f('ix_voice_meetings_owner_id'), table_name='voice_meetings')
    op.drop_table('voice_meetings')
    op.drop_index(op.f('ix_voice_meeting_recordings_state'), table_name='voice_meeting_recordings')
    op.drop_index(op.f('ix_voice_meeting_recordings_owner_id'), table_name='voice_meeting_recordings')
    op.drop_index(op.f('ix_voice_meeting_recordings_meeting_id'), table_name='voice_meeting_recordings')
    op.drop_table('voice_meeting_recordings')
    op.drop_index(op.f('ix_voice_meeting_participants_session_id'), table_name='voice_meeting_participants')
    op.drop_index(op.f('ix_voice_meeting_participants_owner_id'), table_name='voice_meeting_participants')
    op.drop_index(op.f('ix_voice_meeting_participants_meeting_id'), table_name='voice_meeting_participants')
    op.drop_table('voice_meeting_participants')
    op.drop_index(op.f('ix_voice_meeting_messages_owner_id'), table_name='voice_meeting_messages')
    op.drop_index(op.f('ix_voice_meeting_messages_meeting_id'), table_name='voice_meeting_messages')
    op.drop_table('voice_meeting_messages')
    op.drop_index(op.f('ix_voice_events_session_id'), table_name='voice_events')
    op.drop_table('voice_events')
    op.drop_index(op.f('ix_voice_campaigns_status'), table_name='voice_campaigns')
    op.drop_index(op.f('ix_voice_campaigns_owner_id'), table_name='voice_campaigns')
    op.drop_table('voice_campaigns')
    op.drop_index(op.f('ix_voice_campaign_targets_status'), table_name='voice_campaign_targets')
    op.drop_index(op.f('ix_voice_campaign_targets_session_id'), table_name='voice_campaign_targets')
    op.drop_index(op.f('ix_voice_campaign_targets_owner_id'), table_name='voice_campaign_targets')
    op.drop_index(op.f('ix_voice_campaign_targets_campaign_id'), table_name='voice_campaign_targets')
    op.drop_table('voice_campaign_targets')
    op.drop_index(op.f('ix_voice_agents_owner_id'), table_name='voice_agents')
    op.drop_table('voice_agents')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trained_models_owner_id'), table_name='trained_models')
    op.drop_index(op.f('ix_trained_models_name'), table_name='trained_models')
    op.drop_index(op.f('ix_trained_models_active'), table_name='trained_models')
    op.drop_table('trained_models')
    op.drop_index(op.f('ix_system_events_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_source'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_session_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_owner_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_correlation_id'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_system_drafts_status'), table_name='system_drafts')
    op.drop_index(op.f('ix_system_drafts_owner_id'), table_name='system_drafts')
    op.drop_table('system_drafts')
    op.drop_index(op.f('ix_solutions_slug'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_owner_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_category'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_scheduled_reports_source_id'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_owner_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_report_delivery_events_report_id'), table_name='report_delivery_events')
    op.drop_index(op.f('ix_report_delivery_events_created_at'), table_name='report_delivery_events')
    op.drop_table('report_delivery_events')
    op.drop_index(op.f('ix_py8n_systems_owner_id'), table_name='py8n_systems')
    op.drop_index(op.f('ix_py8n_systems_lifecycle'), table_name='py8n_systems')
    op.drop_table('py8n_systems')
    op.drop_index(op.f('ix_pack_registries_owner_id'), table_name='pack_registries')
    op.drop_table('pack_registries')
    op.drop_index(op.f('ix_notification_rules_workflow_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_owner_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_model_systems_owner_id'), table_name='model_systems')
    op.drop_table('model_systems')
    op.drop_index(op.f('ix_model_deployments_workflow_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_owner_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_model_registry_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_enabled'), table_name='model_deployments')
    op.drop_table('model_deployments')
    op.drop_index(op.f('ix_media_sessions_state'), table_name='media_sessions')
    op.drop_index(op.f('ix_media_sessions_ref_id'), table_name='media_sessions')
    op.drop_index(op.f('ix_media_sessions_owner_id'), table_name='media_sessions')
    op.drop_index(op.f('ix_media_sessions_kind'), table_name='media_sessions')
    op.drop_table('media_sessions')
    op.drop_index(op.f('ix_interaction_messages_conversation_id'), table_name='interaction_messages')
    op.drop_table('interaction_messages')
    op.drop_index(op.f('ix_interaction_conversations_state'), table_name='interaction_conversations')
    op.drop_index(op.f('ix_interaction_conversations_owner_id'), table_name='interaction_conversations')
    op.drop_index(op.f('ix_interaction_conversations_channel'), table_name='interaction_conversations')
    op.drop_table('interaction_conversations')
    op.drop_index(op.f('ix_ingestion_states_owner_id'), table_name='ingestion_states')
    op.drop_index(op.f('ix_ingestion_states_dataset_id'), table_name='ingestion_states')
    op.drop_table('ingestion_states')
    op.drop_index(op.f('ix_grant_audit_events_grant_id'), table_name='grant_audit_events')
    op.drop_index(op.f('ix_grant_audit_events_created_at'), table_name='grant_audit_events')
    op.drop_index(op.f('ix_grant_audit_events_app_id'), table_name='grant_audit_events')
    op.drop_table('grant_audit_events')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_owner_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_env_variables_owner_id'), table_name='env_variables')
    op.drop_index(op.f('ix_env_variables_key'), table_name='env_variables')
    op.drop_table('env_variables')
    op.drop_index(op.f('ix_deployment_tokens_owner_id'), table_name='deployment_tokens')
    op.drop_index(op.f('ix_deployment_tokens_key_hash'), table_name='deployment_tokens')
    op.drop_index(op.f('ix_deployment_tokens_deployment_id'), table_name='deployment_tokens')
    op.drop_table('deployment_tokens')
    op.drop_index(op.f('ix_deployment_token_policies_token_id'), table_name='deployment_token_policies')
    op.drop_table('deployment_token_policies')
    op.drop_index(op.f('ix_deployment_token_hits_token_id'), table_name='deployment_token_hits')
    op.drop_table('deployment_token_hits')
    op.drop_index(op.f('ix_deployment_revisions_deployment_id'), table_name='deployment_revisions')
    op.drop_table('deployment_revisions')
    op.drop_index(op.f('ix_datasets_owner_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_dataset_versions_workflow_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_owner_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_created_at'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_dataset_contracts_owner_id'), table_name='dataset_contracts')
    op.drop_index(op.f('ix_dataset_contracts_dataset_id'), table_name='dataset_contracts')
    op.drop_table('dataset_contracts')
    op.drop_index(op.f('ix_dataset_contract_revisions_owner_id'), table_name='dataset_contract_revisions')
    op.drop_index(op.f('ix_dataset_contract_revisions_dataset_id'), table_name='dataset_contract_revisions')
    op.drop_index(op.f('ix_dataset_contract_revisions_created_at'), table_name='dataset_contract_revisions')
    op.drop_table('dataset_contract_revisions')
    op.drop_index(op.f('ix_dashboards_status'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_slug'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_owner_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_name'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_dashboard_audit_events_dashboard_id'), table_name='dashboard_audit_events')
    op.drop_index(op.f('ix_dashboard_audit_events_created_at'), table_name='dashboard_audit_events')
    op.drop_table('dashboard_audit_events')
    op.drop_index(op.f('ix_credentials_owner_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_credential_events_owner_id'), table_name='credential_events')
    op.drop_index(op.f('ix_credential_events_credential_id'), table_name='credential_events')
    op.drop_index(op.f('ix_credential_events_created_at'), table_name='credential_events')
    op.drop_table('credential_events')
    op.drop_index(op.f('ix_channel_queues_state'), table_name='channel_queues')
    op.drop_index(op.f('ix_channel_queues_owner_id'), table_name='channel_queues')
    op.drop_table('channel_queues')
    op.drop_index(op.f('ix_channel_queue_entries_status'), table_name='channel_queue_entries')
    op.drop_index(op.f('ix_channel_queue_entries_session_id'), table_name='channel_queue_entries')
    op.drop_index(op.f('ix_channel_queue_entries_queue_id'), table_name='channel_queue_entries')
    op.drop_index(op.f('ix_channel_queue_entries_owner_id'), table_name='channel_queue_entries')
    op.drop_table('channel_queue_entries')
    op.drop_index(op.f('ix_channel_endpoints_provider'), table_name='channel_endpoints')
    op.drop_index(op.f('ix_channel_endpoints_owner_id'), table_name='channel_endpoints')
    op.drop_table('channel_endpoints')
    op.drop_index(op.f('ix_chain_report_schedules_owner_id'), table_name='chain_report_schedules')
    op.drop_table('chain_report_schedules')
    op.drop_index(op.f('ix_business_processes_owner_id'), table_name='business_processes')
    op.drop_table('business_processes')
    op.drop_index(op.f('ix_business_process_transitions_process_id'), table_name='business_process_transitions')
    op.drop_index(op.f('ix_business_process_transitions_owner_id'), table_name='business_process_transitions')
    op.drop_index(op.f('ix_business_process_transitions_instance_id'), table_name='business_process_transitions')
    op.drop_table('business_process_transitions')
    op.drop_index(op.f('ix_business_process_instances_state'), table_name='business_process_instances')
    op.drop_index(op.f('ix_business_process_instances_process_id'), table_name='business_process_instances')
    op.drop_index(op.f('ix_business_process_instances_owner_id'), table_name='business_process_instances')
    op.drop_table('business_process_instances')
    op.drop_index(op.f('ix_artifacts_workflow_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_execution_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_apps_status'), table_name='apps')
    op.drop_index(op.f('ix_apps_slug'), table_name='apps')
    op.drop_index(op.f('ix_apps_owner_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_name'), table_name='apps')
    op.drop_index(op.f('ix_apps_dataset_id'), table_name='apps')
    op.drop_table('apps')
    op.drop_index(op.f('ix_app_share_grants_token'), table_name='app_share_grants')
    op.drop_index(op.f('ix_app_share_grants_owner_id'), table_name='app_share_grants')
    op.drop_index(op.f('ix_app_share_grants_app_id'), table_name='app_share_grants')
    op.drop_table('app_share_grants')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_api_keys_owner_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
